version: 2.1

orbs:
  maven: circleci/maven@0.0.12
  codecov: codecov/codecov@1.0.2

workflows:
  maven_test:
    jobs:
      - checkout
      - maven/test # checkout, build, test, and upload test results
      - codecov/upload:
          flags: unittest
